spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    # 젠킨스 환경변수 추가
    url: jdbc:mysql://localhost:3306/ggbro?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true       # 데이터베이스 URL
    username : ssafy
    password : ssafy
  jpa:
    hibernate:
      ddl-auto: create-drop                # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost # 젠킨스 환경변수 추가
      port: 6379
  sql:
    init:
      mode: always
      data-locations:
#        - 'classpath:/data_achievement.sql'

# 젠킨스 환경변수 추가
jwt:
  access-key: TestAccessKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  refresh-key: TestRefreshKey111111122222222223333333333333aaaaaaaaabbbbbbbbccccccccdddddddddfqwrqwfqwifjaisfjoihfoiqwflasjdglkkjasdlgjlkasdgjiowejgliasjglasjdgio
  refresh-expiration: 14d
  access-expiration: 14d

# AWS
aws:
  access-key-id: AKIA2UC27RTFNQDD7ICX  # 젠킨스 환경변수 추가
  secret-access-key: LQBplWSgcSQLGpItWNexqfz9RbkpghrMkN/flM9h  # 젠킨스 환경변수 추가
  s3:
    bucket: ggbro # 젠킨스 환경변수 추가

# FLASK
flask:
  server-url: http://k10c206.p.ssafy.io:5000/predict # 젠킨스 환경변수 추가