spring:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop                # ddl 자동 작성 여부
    #      ddl-auto: update                # ddl 자동 작성 여부
    properties:
      hibernate:
        format_sql: true             # 하이버네이트가 실행한 SQL을 출력할 때 보기 좋게 정렬
        show_sql: true               # 하이버네이트가 실행한 SQL을 출력
        jdbc:
          batch_size: 100              #   insert/update 쿼리를 원하는 개수만큼 모아서 DB에 날릴 수 있는 옵션
        default_batch_fetch_size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # DB 드라이버
    url: ${DB_URL}       # 데이터베이스 URL
    username : ${DB_NAME}
    password : ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  springdoc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      configUrl: /v3/api-docs/swagger-config
  jwt:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}
    expired-min:
      refresh-expiration: 14*60*60*1000
      access-expiration: 14*60*60*1000

#server:
#  servlet:
#    context-path: /api/v1

  sql:
    init:
      mode: always
      data-locations:
#        - 'classpath:/data_member.sql'
#        - 'classpath:/data_member_info.sql'
        - 'classpath:/data_pet.sql'
#        - 'classpath:/data_member_pet.sql'
        - 'classpath:/data_achievement.sql'
#        - 'classpath:/data_member_achievement.sql'


